knp_paginator:
    page_range: 5                       # number of links showed in the pagination control (e.g. 1 2 3 4 5)
    default_options:
        page_name: page                 # page query parameter name
        sort_field_name: sort           # sort field query parameter name
        sort_direction_name: direction  # sort direction query parameter name
        filter_field_name: filter       # filter field query parameter name
        filter_value_name: filter_value # filter value query parameter name
        distinct: true                  # ensure distinct results, useful when ORM queries are used
        page_out_of_range: ignore       # what to do when out of range page is requested
    template:
        pagination: 'partials/pagination.html.twig'     # lookup path for your custom template
        sortable: 'knp_paginator/sortable_link.html.twig' # sort link template
        filtration: 'knp_paginator/filtration.html.twig' # filters template